#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
use File::Basename;

my $panel = "manager";

panel_link("passwordopt", $panel);

my $event = "password-modify";

event_link("user-chage-passwd",$event,"30");
event_link("user-passwd-expiration",$event,"35");

 
