#!/usr/bin/perl -wT
# vim: ft=xml ts=4 sw=4 et:
#----------------------------------------------------------------------
# heading : Security
# description : Passwords
# navigation : 2000 2150
#----------------------------------------------------------------------
use strict;
use esmith::TestUtils;
use esmith::FormMagick::Panel::passwordopt;
my $fm = esmith::FormMagick::Panel::passwordopt->new();
$fm->display();
__DATA__
<form title="FORM_TITLE"
header="/etc/e-smith/web/common/head.tmpl"
footer="/etc/e-smith/web/common/foot.tmpl">
<page name="First" 
pre-event="print_status_message()"
post-event="modify_agepar()" >
<description>FORM_DESCRIPTION</description>
 <field type="literal">
            <description>PASSWORD_STRENGTH_DESC</description>
        </field>
<field type="select"   
            id="Admin"
            options=" 'none'=>'NONE', 'normal'=>'NORMAL', 'strong'=>'STRONG'"
            value="get_Admin_value()">
            <label>LABEL_PASSWORD_ADMIN</label>
        </field>
<field type="select"   
            id="Ibays"
            options=" 'none'=>'NONE', 'normal'=>'NORMAL', 'strong'=>'STRONG'"
            value="get_Ibays_value()">
            <label>LABEL_PASSWORD_IBAYS</label>
        </field>
<field type="select"   
            id="Users"
            options=" 'none'=>'NONE', 'normal'=>'NORMAL', 'strong'=>'STRONG'"
            value="get_Users_value()">
            <label>LABEL_PASSWORD_USERS</label>
        </field>

 <field type="literal">
            <description>PASSWORD_AGEING_DESC</description>
        </field>

<field type="select" 
            id="Active" 
            options=" 'no'=>'NO', 'yes'=>'YES'"
            value="get_Active_value()">
            <label>LABEL_AGEING_ACTIVE</label>
        </field>
        <field type="select" 
            id="PwdAge" 
            options="30,60,90,120,180,240,365"
            value="get_PwdAge_value()">
            <label>LABEL_AGEING_VALUE</label>
        </field>
	<field type="select"
            id="PwdWarn"                   
            options="7,10,15"         
            value="get_PwdWarn_value()">     
            <label>LABEL_WARNING_VALUE</label>       
        </field>
	<field type="select"
	    id="LockAccount"
	    options=" 'no'=>'NO', 'yes'=>'YES'"
            value="get_Lock_value()">
            <label>LABEL_ACCOUNT_LOCK</label>
        </field>
	 <field type="select" 
            id="DateReset"
            options=" 'no'=>'NO', 'yes'=>'YES'"
            value="no">  
            <label>LABEL_DATE_RESET</label> 
        </field>

<subroutine src="print_users_table()" />
<subroutine src="print_button('SAVE')" />
</page>
<page name="PASSWORDAGE_PAGE_MODIFY"
pre-event="turn_off_buttons()"
post-event="modify_age()" >
<description>MODIFY_TITLE</description>
<field type="literal" id="User" >
<label>LABEL_USER</label>
</field>
<field type="literal" id="FullName">
<label>LABEL_FULLNAME</label>
</field>
<field type="text" id="PasswordAge">
<label>LABEL_PASSWORDAGE</label>
</field>
<subroutine src="print_button('SAVE')" />
</page>
</form>
